# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.5

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox-travis airflow psycopg2>=2.6.2
  - airflow initdb

# command to run tests, e.g. python setup.py test
script: tox
